#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-mojo-parent
Version  : 34
Release  : 1
URL      : https://github.com/mojohaus/mojo-parent/archive/mojo-parent-34.tar.gz
Source0  : https://github.com/mojohaus/mojo-parent/archive/mojo-parent-34.tar.gz
Source1  : https://repo1.maven.org/maven2/org/codehaus/mojo/mojo-parent/34/mojo-parent-34.pom
Source2  : https://repo1.maven.org/maven2/org/codehaus/mojo/mojo-parent/36/mojo-parent-36.pom
Source3  : https://repo1.maven.org/maven2/org/codehaus/mojo/mojo-parent/38/mojo-parent-38.pom
Source4  : https://repo1.maven.org/maven2/org/codehaus/mojo/mojo-parent/40/mojo-parent-40.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 EPL-1.0
Requires: mvn-mojo-parent-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-mojo-parent package.
Group: Data

%description data
data components for the mvn-mojo-parent package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/34
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/34

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/36
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/36

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/38
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/38

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/40
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/40


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/34/mojo-parent-34.pom
/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/36/mojo-parent-36.pom
/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/38/mojo-parent-38.pom
/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/40/mojo-parent-40.pom
