#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-mojo-parent
Version  : 34
Release  : 4
URL      : https://github.com/mojohaus/mojo-parent/archive/mojo-parent-34.tar.gz
Source0  : https://github.com/mojohaus/mojo-parent/archive/mojo-parent-34.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Source2  : https://repo1.maven.org/maven2/org/codehaus/mojo/mojo-parent/28/mojo-parent-28.pom
Source3  : https://repo1.maven.org/maven2/org/codehaus/mojo/mojo-parent/32/mojo-parent-32.pom
Source4  : https://repo1.maven.org/maven2/org/codehaus/mojo/mojo-parent/33/mojo-parent-33.pom
Source5  : https://repo1.maven.org/maven2/org/codehaus/mojo/mojo-parent/34/mojo-parent-34.pom
Source6  : https://repo1.maven.org/maven2/org/codehaus/mojo/mojo-parent/36/mojo-parent-36.pom
Source7  : https://repo1.maven.org/maven2/org/codehaus/mojo/mojo-parent/38/mojo-parent-38.pom
Source8  : https://repo1.maven.org/maven2/org/codehaus/mojo/mojo-parent/39/mojo-parent-39.pom
Source9  : https://repo1.maven.org/maven2/org/codehaus/mojo/mojo-parent/40/mojo-parent-40.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 EPL-1.0
Requires: mvn-mojo-parent-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-mojo-parent package.
Group: Data

%description data
data components for the mvn-mojo-parent package.


%prep
%setup -q -n mojo-parent-mojo-parent-34

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/maven-metadata-central.xml

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/28
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/28/mojo-parent-28.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/32
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/32/mojo-parent-32.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/33
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/33/mojo-parent-33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/34
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/34/mojo-parent-34.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/36
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/36/mojo-parent-36.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/38
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/38/mojo-parent-38.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/39
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/39/mojo-parent-39.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/40
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/40/mojo-parent-40.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/codehaus/mojo/maven-metadata-central.xml
/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/28/mojo-parent-28.pom
/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/32/mojo-parent-32.pom
/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/33/mojo-parent-33.pom
/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/34/mojo-parent-34.pom
/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/36/mojo-parent-36.pom
/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/38/mojo-parent-38.pom
/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/39/mojo-parent-39.pom
/usr/share/java/.m2/repository/org/codehaus/mojo/mojo-parent/40/mojo-parent-40.pom
